[tool.poetry]
name = "chibi-bot"
version = "1.0.0"
description = "Telegram bot for Chibi collection"
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "^20.7"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
