services:
  - type: web
    name: telegram-chibi-bot
    env: python
    plan: free
    buildCommand: pip install -r chibi-bot/requirements.txt
    startCommand: python chibi-bot/bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
