services:
  - type: web
    name: telegram-chibi-bot
    env: python
    plan: free
    buildCommand: cd chibi-bot && pip install -r requirements.txt
    startCommand: cd chibi-bot && python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
